name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: Deployment
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
    - name: Prepare JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@13.2
      with:
        cli: 1.12.1.1538
    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: v1-${{ hashFiles('./deps.edn') }}-deploy
        restore-keys: |
          v1-${{ hashFiles('./deps.edn') }}-
          v1-
    - name: Build Macaw
      run: clojure -T:build jar
      env:
        GITHUB_SHA: ${{ env.GITHUB_SHA }}
    - name: Deploy Macaw
      run: clojure -T:build deploy
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
